mappings:
    depth_hold: 0
    switch: 1
    manual: 2
    stabilize: 3
    mount_dec: 4
    mount_inc: 5
    shift: 6

    disarm: 8
    arm: 9
    mount_center: 10



    light_dec: 14
    light_inc: 15
    gain_dec: 16
    gain_inc: 17







# arm: 512 (9)
# disarm: 256 (8)
# gain_inc 14
# gain_dec 15
# manual 2
# alt_hold 0
# stabilize 3

#mappings:
#    arm: 9
#    disarm: 8
#    depth_hold: 3
#    manual: 2
#    stabilize: 1
#    light_inc: 15
#    light_dec: 14
#    gain_inc: 17
#    gain_dec: 16
#    mount_center: 10
#    mount_inc: 5
#    mount_dec: 4
#    shift: 6
#    input_hold: 1

# DEFAULTS
# stabilize 2**1
# pos_hold 2**2
# alt_hold 2**3
# disarm 2**4
# - 2**5
# arm 2**6
# - 2**7
# - 2**8
# - 2**9
# - 2**10
# gain_inc 2**11
# gain_dec 2**12
# - 2**13
# - 2**14
# - 2**15

