accel_x_kp: 1.0
accel_x_ki: 0.0
accel_x_kd: 0.0
accel_x_sat: 1.0
accel_y_kp: 1.0
accel_y_ki: 0.0
accel_y_kd: 0.0
accel_y_sat: 1.0
accel_z_kp: 1.0
accel_z_ki: 0.0
accel_z_kd: 0.0
accel_z_sat: 1.0
accel_r_kp: 1.0
accel_r_ki: 0.0
accel_r_kd: 0.0
accel_r_sat: 1.0
vel_x_kp: 100.0
vel_x_ki: 1
vel_x_kd: 0.0
vel_x_sat: 10
vel_x_lim: 0.5
vel_y_kp: 100.0
vel_y_ki: 1
vel_y_kd: 0.0
vel_y_sat: 10
vel_y_lim: 0.2
vel_z_kp: 100.0
vel_z_ki: 1
vel_z_kd: 0.0
vel_z_sat: 10
vel_z_lim: 0.5
vel_r_kp: 10.0
vel_r_ki: 0.0001
vel_r_kd: 0.1
vel_r_sat: 1.0
vel_r_lim: 0.5
pos_x_kp: 1.0
pos_x_ki: 0.0
pos_x_kd: 0.0
pos_x_sat: 1.0
pos_y_kp: 1.0
pos_y_ki: 0.0
pos_y_kd: 0.0
pos_y_sat: 1.0
pos_z_kp: 1.0
pos_z_ki: 0.0
pos_z_kd: 0.0
pos_z_sat: 1.0
pos_r_kp: 1.0
pos_r_ki: 0.0
pos_r_kd: 0.0
pos_r_sat: 1.0