mappings:
    arm: 9
    disarm: 8
    depth_hold: 0
    manual: 2
    stabilize: 3
    light_inc: 15
    light_dec: 14
    gain_inc: 17
    gain_dec: 16
    mount_center: 10
    mount_inc: 5
    mount_dec: 4
    shift: 6
    input_hold: 1

# arm: 512 (9)
# disarm: 256 (8)
# gain_inc 14
# gain_dec 15
# manual 2
# alt_hold 0
# stabilize 3
